import request from '@/utils/request'

const unwrap = (promise) => promise.then(response => response.data)

export const getXyDashboard = () => unwrap(request.get('/xy/dashboard'))
export const getXyMembers = (keyword) => unwrap(request.get('/xy/members', { params: { keyword } }))
export const getXyReservations = (date, status) => unwrap(request.get('/xy/reservations', { params: { date, status } }))
export const verifyXyReservation = (verifyCode) => unwrap(request.post(`/xy/reservations/verify/${encodeURIComponent(verifyCode)}`))
export const verifyXyMember = (verifyCode) => unwrap(request.post(`/xy/members/verify/${encodeURIComponent(verifyCode)}`))
export const getXyProducts = () => unwrap(request.get('/xy/products'))
export const saveXyProduct = (product) => unwrap(product.productId ? request.put('/xy/products', product) : request.post('/xy/products', product))
export const getXyMemberDiscountSettings = () => unwrap(request.get('/xy/member-discount-settings'))
export const saveXyMemberDiscountSettings = (data) => unwrap(request.put('/xy/member-discount-settings', data))
export const getXyReservationConfiguration = () => unwrap(request.get('/xy/reservation-configuration'))
export const saveXyStore = (data) => unwrap(data.storeId ? request.put('/xy/stores', data) : request.post('/xy/stores', data))
export const saveXySlot = (data) => unwrap(data.slotId ? request.put('/xy/reservation-slots', data) : request.post('/xy/reservation-slots', data))
export const saveXySeat = (data) => unwrap(data.seatId ? request.put('/xy/seats', data) : request.post('/xy/seats', data))
export const saveXyPlan = (data) => unwrap(data.planId ? request.put('/xy/membership-plans', data) : request.post('/xy/membership-plans', data))
export const getXyFinance = () => unwrap(request.get('/xy/finance'))
export const getXyStaff = () => unwrap(request.get('/xy/staff'))
export const getXyVerificationRecords = () => unwrap(request.get('/xy/verification-records'))
export const getXyOrders = () => unwrap(request.get('/xy/orders'))
export const shipXyOrder = (orderNo) => unwrap(request.post(`/xy/orders/${encodeURIComponent(orderNo)}/ship`))
export const getXyOfflinePayments = (status = 'PENDING') => unwrap(request.get('/xy/offline-payments', { params: { status } }))
export const confirmXyOfflinePayment = (paymentNo) => unwrap(request.post(`/xy/offline-payments/${encodeURIComponent(paymentNo)}/confirm`))
export const closeXyOfflinePayment = (paymentNo) => unwrap(request.post(`/xy/offline-payments/${encodeURIComponent(paymentNo)}/close`))
export const getXyAfterSales = () => unwrap(request.get('/xy/after-sales'))
export const approveXyAfterSale = (no) => unwrap(request.post(`/xy/after-sales/${encodeURIComponent(no)}/approve`))
export const rejectXyAfterSale = (no) => unwrap(request.post(`/xy/after-sales/${encodeURIComponent(no)}/reject`))
export const completeXyOfflineRefund = (no) => unwrap(request.post(`/xy/after-sales/${encodeURIComponent(no)}/complete-offline-refund`))
export const restockXyReturnedAfterSale = (no) => unwrap(request.post(`/xy/after-sales/${encodeURIComponent(no)}/restock`))
